### ISSUE TITLE
Refactor make_decoder template function to make code neater

### ISSUE THREAD

**Issue by bigfatwhale** [bigfatwhale/bats_pitch_parser#5]
RIght now make_decoder has to be specialized for AddOrderMsgDecoder and TradeMsgDecoder, because they have long/short versions of their messages. 

It makes the code-base quite ugly. Can we refactor the make everything more uniform? Static typing seems to make this more troublesome than compared to languages like Python. In Python just wrapping things up in another function would just work, and make the code clean.

**Comment by wlyeow** [comment]
I think this is completed?

**Comment by bigfatwhale** [comment]
Oh yes i guess so, let me close it.
